server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  type-aliases-package: cn.bnz.service.pojo
  
  http://localhost:8088/consumer/item/findAll
  
  
  http://localhost:8008/consumer/item/findAll
